# Generated by Django 3.1.7 on 2021-03-05 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_auto_20210305_0641"),
        ("account", "0002_auto_20210305_0642"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="employee_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.employeecategory",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_employee",
            field=models.BooleanField(default=False),
        ),
    ]
