# Generated by Django 3.1.7 on 2021-03-05 14:57

import account.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_auto_20210305_0650"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="document",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=account.utils.employee_document_location,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_verified_employee",
            field=models.BooleanField(default=False),
        ),
    ]
