version: "3.8"
services:
    redis:
        restart: unless-stopped
    db:
        volumes:
          - ./dockerfiles/init_sql_dev.sh:/docker-entrypoint-initdb.d/init_sql_dev.sh
        env_file: ./dockerfiles/.env.dev
        
    corecare_backend:
        build: 
            dockerfile: ./dockerfile
        restart: unless-stopped
        env_file: ./dockerfiles/.env.dev
        volumes: 
            - .:/corecare_backend
        ports: 
            - 8000:8000
        image: corecare_backend:dev
        command: bash -c 'while !</dev/tcp/db/5432; do sleep 5; done; python manage.py runserver 0.0.0.0:8000'
    
    celery:
        build: 
            dockerfile: ./dockerfile
        restart: unless-stopped
        env_file: ./dockerfiles/.env.dev
        command: celery -A backend worker -l INFO
        volumes: 
            - .:/corecare_backend
