version: "3.8"
services:
    redis:
        image: redis:alpine 
        container_name: corecare_redis

    db:
        volumes: 
            - pgdata:/var/lib/postgresql/data
        image: postgres
        container_name: corecare_postgres
        ports:
        - 5432:5432

    corecare_backend:
        build: 
            context: .
        container_name: corecare_backend
        depends_on: 
            - db
            - redis
        
    celery:
        build: 
            context: .
        container_name: corecare_celery
        depends_on: 
            - db    
            - redis
            - corecare_backend
volumes:
  pgdata:
