# Generated by Django 3.1.7 on 2021-02-25 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="couponcode",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name="couponcode",
            name="category",
        ),
        migrations.AddField(
            model_name="couponcode",
            name="category",
            field=models.ManyToManyField(to="api.EmployeeCategory"),
        ),
    ]
