# Generated by Django 3.1.7 on 2021-02-25 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20210225_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='api.EmployeeCategory'),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
