# Generated by Django 3.1.7 on 2021-02-25 18:31

from django.db import migrations, models

import api.utils


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_employeecategory_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeecategory",
            name="icon",
            field=models.FileField(
                default="Employee Category/default.svg",
                upload_to=api.utils.EmployeeIconLocation,
            ),
        ),
    ]
