# Generated by Django 3.1.7 on 2021-02-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20210225_1031"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeecategory",
            name="icon",
        ),
    ]
