# Generated by Django 3.1.7 on 2021-02-28 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_servicesubcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesubcategory",
            name="service_specialist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.employeecategory",
            ),
        ),
    ]
