# Generated by Django 3.1.7 on 2021-02-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_servicesubcategory_service_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesubcategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
