# Generated by Django 3.1.7 on 2021-02-28 13:50

from django.db import migrations, models

import api.utils


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.ImageField(
                default="default_service.jpg", upload_to=api.utils.ServiceIconLocation
            ),
        ),
    ]
