# Generated by Django 3.1.7 on 2021-02-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_service_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
    ]
