# Generated by Django 3.1.7 on 2021-02-28 14:01

from django.db import migrations, models

import api.utils


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_remove_service_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="icon",
            field=models.ImageField(
                default="Service Images/default-service.jpg",
                upload_to=api.utils.ServiceIconLocation,
            ),
        ),
    ]
