# Generated by Django 3.1.7 on 2021-02-28 14:04

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_service_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicesubcategory",
            name="icon",
            field=models.ImageField(
                default="Service SubCategory Images/default.jpg",
                upload_to=api.utils.SubcategoryIconLocation,
            ),
        ),
    ]
