# Generated by Django 3.1.7 on 2021-02-28 14:07

from django.db import migrations, models

import api.utils


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_remove_servicesubcategory_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesubcategory",
            name="icon",
            field=models.ImageField(
                default="Service SubCategory Images/default.jpg",
                upload_to=api.utils.SubcategoryIconLocation,
            ),
        ),
    ]
