# Generated by Django 3.1.7 on 2021-02-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_auto_20210228_0939"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeecategory",
            options={},
        ),
    ]
