# Generated by Django 3.1.7 on 2021-02-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210228_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponcode',
            options={'ordering': ('code',)},
        ),
    ]
