# Generated by Django 3.1.7 on 2021-03-05 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210305_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryreview',
            name='star',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
