# Generated by Django 3.1.7 on 2021-03-05 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_categoryreview_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryreview',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employeecategory'),
        ),
    ]
