# Generated by Django 3.1.7 on 2021-03-07 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_categoryreview_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryreview",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_reviews",
                to="api.employeecategory",
            ),
        ),
    ]
