# Generated by Django 3.1.7 on 2021-04-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_employeecategory_hiring"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("number", models.CharField(db_index=True, max_length=100)),
                ("email", models.EmailField(db_index=True, max_length=100)),
                ("detail", models.TextField(max_length=500)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
