# Generated by Django 3.1.7 on 2021-05-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_partnerrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryreview',
            options={'ordering': ('-created',)},
        ),
    ]
