# Generated by Django 3.1.7 on 2021-05-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20210525_0740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryreview',
            options={'ordering': ('created',)},
        ),
    ]
