# Generated by Django 3.2.4 on 2021-06-16 09:01

from django.db import migrations, models

import api.utils


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_auto_20210525_0741"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicesubcategory",
            name="placeholder",
            field=models.ImageField(
                null=True, upload_to=api.utils.SubcategoryPlaceholderLocation
            ),
        ),
    ]
