# Generated by Django 3.2.4 on 2021-06-16 09:15

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_servicesubcategory_placeholder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicesubcategory",
            name="placeholder",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api.utils.SubcategoryPlaceholderLocation,
            ),
        ),
    ]
