# Generated by Django 3.2.4 on 2021-06-16 12:38

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_alter_servicesubcategory_placeholder"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="placeholder",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api.utils.SubcategoryPlaceholderLocation,
            ),
        ),
    ]
