# Generated by Django 3.1.7 on 2021-04-01 19:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_order_fullfill_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='order',
            name='fullfill_by',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 4, 19, 29, 24, 952322, tzinfo=utc)),
        ),
    ]
