# Generated by Django 3.1.7 on 2021-04-06 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_auto_20210403_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fullfill_by',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 10, 52, 12, 402007, tzinfo=utc)),
        ),
    ]
