# Generated by Django 3.1.7 on 2021-04-06 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_auto_20210406_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fullfill_by',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 13, 40, 54, 159687, tzinfo=utc)),
        ),
    ]
