# Generated by Django 3.1.7 on 2021-04-06 13:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_auto_20210406_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fullfill_by',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 13, 43, 48, 888248, tzinfo=utc)),
        ),
    ]
