# Generated by Django 3.1.7 on 2021-04-06 15:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_auto_20210406_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fullfill_by',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 15, 1, 59, 809282, tzinfo=utc)),
        ),
    ]
