# Generated by Django 3.1.7 on 2021-04-07 09:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_auto_20210407_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fullfill_by',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 9, 8, 30, 980514, tzinfo=utc)),
        ),
    ]
