# Generated by Django 3.1.7 on 2021-05-22 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_partnerrequest"),
        ("blog", "0002_auto_20210522_2029"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_posts",
                to="api.employeecategory",
            ),
        ),
    ]
