# Generated by Django 3.1.7 on 2021-05-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210529_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='image',
            new_name='upload',
        ),
    ]
