# Generated by Django 3.1.7 on 2021-05-30 12:31

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210529_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='default_blog.jpg', upload_to=blog.utils.blog_image_location),
        ),
    ]
