# Generated by Django 3.1.7 on 2021-05-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_comment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
