# Generated by Django 3.1.7 on 2021-05-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_auto_20210531_2204"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
