# Generated by Django 3.2.4 on 2021-06-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_auto_20210531_2307"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("created",)},
        ),
    ]
