# Generated by Django 3.2.4 on 2021-06-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_post_placeholder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=400),
        ),
    ]
