# Generated by Django 3.1.7 on 2021-03-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_auto_20210326_0704"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="category",
        ),
    ]
