# Generated by Django 3.1.7 on 2021-03-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
    ]
