# Generated by Django 3.1.7 on 2021-03-27 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_auto_20210321_0202"),
        ("cart", "0010_auto_20210327_0927"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.service"
            ),
        ),
    ]
