# Generated by Django 3.1.7 on 2021-03-28 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20210328_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fullfill_by',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 14, 34, 38, 263784, tzinfo=utc)),
        ),
    ]
