# Generated by Django 3.1.7 on 2021-04-07 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0012_auto_20210328_0237"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("-created",)},
        ),
        migrations.AddField(
            model_name="order",
            name="fullfill_by",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 4, 10, 9, 11, 0, 601983, tzinfo=utc)
            ),
        ),
    ]
