# Generated by Django 3.1.7 on 2021-04-03 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_auto_20210401_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fullfill_by',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 14, 19, 34, 114589, tzinfo=utc)),
        ),
    ]
