# Generated by Django 3.1.7 on 2021-04-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0014_auto_20210407_0211"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="fullfill_by",
        ),
    ]
