# Generated by Django 3.1.7 on 2021-04-07 10:48

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0018_auto_20210407_0346"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="complete_by",
        ),
        migrations.AddField(
            model_name="order",
            name="fullfill_by",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 4, 10, 10, 48, 32, 192889, tzinfo=utc)
            ),
        ),
    ]
