# Generated by Django 3.1.7 on 2021-04-07 10:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0019_auto_20210407_0348"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="fullfill_by",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 4, 10, 10, 48, 45, 880250, tzinfo=utc)
            ),
        ),
    ]
