# Generated by Django 3.1.7 on 2021-04-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_auto_20210407_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fullfill_by',
            field=models.DateTimeField(default='django.utils.timezone.now'),
        ),
    ]
