# Generated by Django 3.1.7 on 2021-05-19 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_partnerrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0024_auto_20210407_0436"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_orders",
                to="api.employeecategory",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
